### ISSUE TITLE
Add Support for Tenant Variable Association

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#182]
This issue requests adding support for associating tenants with variables. Currently, an investigation is underway to determine how to best implement this support through configuration. This issue will track observations relating to this investigation.

Dependency: [#62](https://github.com/OctopusDeploy/go-octopusdeploy/issues/62)

**Comment by dalmirog** [comment]
+1 we found ourselves needing this to move on with our effort to migrate all our Octopus to Terraform.

**Comment by jbristowe** [comment]
Here is the proposed configuration:

```
resource "octopusdeploy_tenant" "test-tenant" {
  name = "test-tenant"
  tenant_tags = [ "tag-set/tag" ]

  common_variable {
    id                      = octopusdeploy_variable.test-variable.id
    library_variable_set_id = octopusdeploy_library_variable_set.test.id
    value                   = "test-value"
  }

  project_environment {
    environments = [ "Environments-123" ]
    project_id   = "Projects-123"
  }

  project_variable {
    environment_id = "Environments-123"
    project_id     = "Projects-123"
    template_id    = "164c8bb5-3493-4329-9b69-a643594d5910"
    value          = "test-value"
  }
}
```

This change adds two (2) new attributes — `common_variable` and `project_variable`. They define values for variables applied to a tenant. A default value is applied if they are missing.

**Comment by droyad** [comment]
I would actually make the variables resources in of themselves. That way you can have some in terraform and some entered via the UI without them being clobbered. Say you have a template but you want the end user to customise some of them as you don't want to manage them via Terraform (e.g. Production passwords).

Also gazing into the crystal ball, we want to make variables resources directly in the Octopus API instead of exposing them as a VariableSet.

From a previous discussion ([internal link](https://octopusdeploy.slack.com/archives/CDTCSG469/p1596493467008000)), there are three options:
1) Resource per variable set. The server API does this currently. Mixing terraform and UI configured variable would be difficult, you have to add ignore rules to your terraform resource
2) Resource per variable name. The UI currently treats variables this way, it groups them by name. Each name can have multiple values. This makes sense to the user. However I think the the most common use case would be test scoped variables in terraform and prod variable in Octopus UI (with the same name)
3) Resource per variable. Top flexibility but loses the ability to say "remove any variables added by the user"

**Comment by jbristowe** [comment]
Something like this?

```hcl
resource "octopusdeploy_tenant_common_variable" "variable-foo" {
  library_variable_set_id = "LibraryVariableSets-123"
  tenant_id               = "Tenants-123"
  value                   = "test-value"
  variable_id             = "666f70cd-ea9f-d532-e759-775cf86f19b4"
}

resource "octopusdeploy_tenant_project_variable" "variable-bar" {
  environment_id = "Environments-123"
  project_id     = "Projects-123"
  template_id    = "164c8bb5-3493-4329-9b69-a643594d5910"
  tenant_id      = "Tenants-123"
  value          = "test-value"
}
```

**Comment by droyad** [comment]
Yeh. Then you can also group the tenant's project variable with the project config instead of the tenant config if you want.
