### ISSUE TITLE
data.octopusdeploy_library_variable_sets not finding anything

### ISSUE THREAD

**Issue by mbenson** [OctopusDeployLabs/terraform-provider-octopusdeploy#207]
**Describe the bug**
I have several library variable sets defined, but `data "octopusdeploy_library_variable_sets"` finds nothing no matter what value I specify for its `name` parameter.

**Steps to reproduce**
Create a variable set named e.g. `tenant_settings`. Then the following TF config:
```
data "octopusdeploy_library_variable_sets" "tenant_settings" {
  name = "tenant_settings"
}
output "tenant_settings" {
  value = data.octopusdeploy_library_variable_sets.tenant_settings
}
```
yields, from `terraform plan`:

```
Changes to Outputs:
  + tenant_settings = {
      + id   = null
      + name = null
    }
```

**Expected behavior**
I would rather expect both `id` and `name` properties to be populated in the output, permitting me to learn the ID from the name.

**Environment and versions:**
- OS: OSX
- Octopus Server Version: https://octopus.com/downloads/2021.1.7379
- Terraform Version: `1.0.0`
- Octopus Terraform Provider Version: `0.7.40`

**Additional context**
Attempting to use a library variable set as a temporary workaround for https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/182

**Comment by ShawnPollock** [comment]
Can confirm, I am facing the same exact issue.

**Comment by pemaxim** [comment]
I guess it may be tied to trying to retrieve variable set from non-default Space. Since there is no parameter to select Space in data [octopusdeploy_library_variable_sets](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/data-sources/library_variable_sets), I think, it tries to retrieve variable set data from default `Spaces-1`.

@mbenson @ShawnPollock Anyway, as a workaround solution you can use [http](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http) to retrieve all variable sets data and then get the required one:

```
variable octopus_address = {
  default = "{OCTOPUS_URL}"
}

variable octopus_space_id = {
  default = "{SPACE_ID}"
}

variable octopus_key = {
  default = "{APIKEY}"
}

data "http" "all_variables_sets" {
  url = "${var.octopus_address}/api/${var.octopus_space_id}/libraryvariablesets/all"

  request_headers = {
    Accept           = "application/json"
    X-Octopus-ApiKey = var.octopus_key
  }
}

locals {
    
  all_variables_sets = {
    for item in lookup(jsondecode(data.http.all_variables_sets.body), "Items") : item.Name => item
  }

}

```

Now, you can retrieve your variable set object:

```
local.all_variables_sets["{YOUR_VARIABLE_SET_NAME}"]
```

**Comment by peter-dolkens** [comment]
Thanks @pemaxim  - just came here to report this too

**Comment by jbristowe** [comment]
Apologies. I looked into this and quickly realised that this was never implemented properly. 🤦 I'm issuing a fix for this.

**Comment by mbenson** [comment]
@jbristowe thanks!

**Comment by mbenson** [comment]
@pemaxim I never got a chance to try your workaround but I will keep it in mind as a general approach in the future; thanks!
