### ISSUE TITLE
Lack of idempotency

### ISSUE THREAD

**Issue by itaispiegel** [OctopusDeployLabs/terraform-provider-octopusdeploy#549]
**Describe the bug**
The provider isn't idempotent. When trying to use the provider to apply a configuration of resources which already exist, an error is raised saying that the resource already exists.

**Steps to reproduce**
1. Create a tenant manually on the website. Say its name is "tenant".
2. Define the following resource:
```hcl
resource "octopusdeploy_tenant" "tenant" {
  name        = "tenant"
}
```
3. Apply the configuration, and expect to receive the following output:
```
|
│ Error: octopus deploy api returned an error on endpoint /api/Spaces-1/tenants - [A tenant with this name already exists. Please choose a different name.]
│ 
│   with octopusdeploy_tenant.tenant,
│   on main.tf line 17, in resource "octopusdeploy_tenant" "tenant":
│   17: resource "octopusdeploy_tenant" "tenant" {
│ 
╵
```

**Expected behavior**
The expected behavior is that Terraform should return without making any changes.

**Environment and versions:**
- OS: OSX
- Octopus Server Version: 2023.4.4798
- Terraform Version: v1.5.2
- Octopus Terraform Provider Version: v0.12.7

**Comment by zentron** [comment]
This looks to no longer be ocurring

**Comment by mjhilton** [comment]
> The expected behavior is that Terraform should return without making any changes.

I'm not sure I agree with this as the expected behaviour. We have a bunch of validation rules in the Octopus domain which drive whether an entity can be created or not. For the given example of a `Tenant`, there's a uniqueness rule on the Tenant's name. These rules are in place regardless of which interface you use to manage the resource: Octopus UI, CLI, REST API or Terraform. It seems reasonable that they're being enforced in this way.

To me, "idempotency" in this context means that the provider will bring the resources into the same state, no matter how many times a `plan`/`apply` command is run. We see this when you create a tenant using the above repro but without first creating it in the UI - the initial plan/apply works correctly to create the resource, and subsequent plan/apply cycles see that the resource is in the correct state, and so do nothing. 

I agree that we don't have good discoverability of these validation rules, and so you might find this behaviour frustrating or surprising, and you kind of have to get to the right state by trial-and-error. We'd like to make that experience better in future.

**Comment by mjhilton** [comment]
For this immediate issue, I believe that the `terraform import` command is what you should be using to bring your Terraform state into alignment with the state of the tenants in Octopus (modify for whatever resource you're experiencing similar problems on).

After step 3 in the repro above, you would continue with:

1. Use the `terraform import` command to align your TF state with the existing resource, using the ID of the Tenant you discover through the UI/API
```
terraform import "octopusdeploy_tenant.tenant" "Tenants-1"
```
6. Receive confirmation that Terraform has imported the state to your state store:
```
octopusdeploy_tenant.tenant: Importing from ID "Tenants-1"...
octopusdeploy_tenant.tenant: Import prepared!
  Prepared octopusdeploy_tenant for import
octopusdeploy_tenant.tenant: Refreshing state... [id=Tenants-1]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
2. Run `terraform plan` or `terraform apply` and see that everything is now aligned:
```
octopusdeploy_tenant.tenant: Refreshing state... [id=Tenants-1]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
