### ISSUE TITLE
Support project deployment settings

### ISSUE THREAD

**Issue by hans-m-song** [OctopusDeployLabs/terraform-provider-octopusdeploy#618]
**Is your feature request related to a problem? Please describe.**

Currently, project deployment settings can only be managed by manual click-ops via the UI. We would like to be able to configure these settings via Terraform, primarily the release versioning template.

**Describe the solution you'd like**

Support managing deployment settings for a project via Terraform.

**Describe alternatives you've considered**

N/A

**Additional context**

![image](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/assets/21118015/63ef0295-3900-4066-a7b4-1cf1ff6d5d38)

**Comment by mjhilton** [comment]
I've had a look into this, and though I'm not sure what the functionality was when the issue was reported, it looks like you can do most of these now - just not how you're expecting to. 

Majority of the Deployment Settings can be configured on the `octopusdeploy_project` resource, with the following mapping to what you see in the UI:

| Octopus Server UI | TFP Resource Field |
|-|-|
| Release Versioning | `octopusdeploy_project.versioning_strategy` |
| Release Notes Template | `octopusdeploy_project.release_notes_template` | 
| Deployment Targets Required | `octopusdeploy_project.connectivity_policy.allow_deployments_to_no_targets` | 
| Transient Deployment Targets (Unhealthy) | `octopusdeploy_project.connectivity_policy.exclude_unhealthy_targets` | 
| Transient Deployment Targets (Unavailable) | `octopusdeploy_project.connectivity_policy.skip_machine_behavior` <br />`octopusdeploy_project.connectivity_policy.target_roles` | 
| Deployment Changes Template | `octopusdeploy_project.deployment_changes_template` |
| Default Failure Mode | `octopusdeploy_project.default_guided_failure_mode` | 
| Force Package Download | Doesn't seem to be supported |

I'm going to close this issue, let us know if you have any further problems in this area.
